import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:bedjoekopi/cubit/cubit.dart';
import 'package:bedjoekopi/models/models.dart';
import 'package:bedjoekopi/shared/shared.dart';
import 'package:bedjoekopi/widgets/widgets.dart';
import 'package:flutter/material.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:supercharged/supercharged.dart';
import 'package:get/get.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_barcode_scanner/flutter_barcode_scanner.dart';
import 'package:image_picker/image_picker.dart';
import 'package:http/http.dart' as http;
import 'package:url_launcher/url_launcher.dart';

part 'general_page.dart';
part 'sign_in_page.dart';
part 'sign_up_page.dart';
part 'address_page.dart';
part 'main_page.dart';
part 'coffee_page.dart';
part 'coffee_detail_page.dart';
part 'coffee_qr_detail_page.dart';
part 'payment_page.dart';
part 'illustration_page.dart';
part 'success_order_page.dart';
part 'success_sign_up_page.dart';
part 'order_history_page.dart';
part 'profile_page.dart';
part 'forgot_password_page.dart';
part 'about_page.dart';
part 'payment_method_page.dart';
