name: bedjoekopi
description: A new Coffeeshop project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.13.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.0
  supercharged: ^2.0.0
  google_fonts: ^4.0.3
  flutter_spinkit: ^5.0.0
  get: ^4.1.4
  material_design_icons_flutter: ^5.0.6295
  intl: ^0.17.0
  equatable: ^2.0.0
  flutter_barcode_scanner: ^2.0.0
  http: ^0.13.3
  image_picker: ^0.8.1+3
  url_launcher: ^6.0.9
  platform: ^3.1.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/arrow_back.png
    - assets/arrow_back_white.png
    - assets/bike.png
    - assets/btn_add.png
    - assets/btn_min.png
    - assets/food_whises.png
    - assets/ic_home.png
    - assets/ic_home_normal.png
    - assets/ic_order.png
    - assets/ic_order_normal.png
    - assets/ic_profile.png
    - assets/ic_profile_normal.png
    - assets/ic_scan_me.png
    - assets/logo.png
    - assets/machine-coffee.png
    - assets/payment.png
    - assets/photo.png
    - assets/photo_border.png
    - assets/right_arrow.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
